//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_type
    {
        public account_type()
        {
            this.chart_of_accounts = new HashSet<chart_of_accounts>();
        }
    
        public int account_type_id { get; set; }
        public string account_name { get; set; }
        public int type { get; set; }
        public string range_start { get; set; }
        public string range_end { get; set; }
        public bool active { get; set; }
    
        public virtual ref_account_type ref_account_type { get; set; }
        public virtual ICollection<chart_of_accounts> chart_of_accounts { get; set; }
    }
}
