//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public contact()
        {
            this.expenses = new HashSet<expense>();
            this.invoices = new HashSet<invoice>();
        }
    
        public int contact_id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string suffix { get; set; }
        public string company { get; set; }
        public string display_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string fax { get; set; }
        public string other { get; set; }
        public string website { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public Nullable<bool> shipping_address_same { get; set; }
        public string ship_address { get; set; }
        public string ship_postcode { get; set; }
        public string ship_city { get; set; }
        public string ship_state { get; set; }
        public string ship_country { get; set; }
        public string trade_registration_no { get; set; }
        public string gst_number { get; set; }
        public Nullable<System.DateTime> gst_status_verified_date { get; set; }
        public string notes { get; set; }
        public bool active { get; set; }
        public int contact_type { get; set; }
    
        public virtual ref_contact_type ref_contact_type { get; set; }
        public virtual ICollection<expense> expenses { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
