//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public expense()
        {
            this.expense_item = new HashSet<expense_item>();
        }
    
        public int expense_id { get; set; }
        public int contact_id { get; set; }
        public int paid_by_account_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public Nullable<bool> is_bill { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<System.DateTime> bill_number { get; set; }
        public Nullable<System.DateTime> payment_due_date { get; set; }
        public Nullable<int> ref_payment_made_type { get; set; }
        public string ref_no { get; set; }
        public Nullable<int> tax_id { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<bool> amount_tax_inclusive { get; set; }
        public decimal subtotal { get; set; }
        public decimal net_amount { get; set; }
        public string note { get; set; }
        public System.DateTime auto_entry_date { get; set; }
    
        public virtual chart_of_accounts chart_of_accounts { get; set; }
        public virtual contact contact { get; set; }
        public virtual ref_payment_made_type ref_payment_made_type1 { get; set; }
        public virtual tax_code tax_code { get; set; }
        public virtual ICollection<expense_item> expense_item { get; set; }
    }
}
