//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_ledger
    {
        public int general_ledger_id { get; set; }
        public int account_id { get; set; }
        public Nullable<decimal> opening_debit_balance { get; set; }
        public Nullable<decimal> opening_credit_balance { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> auto_enty_date { get; set; }
    
        public virtual chart_of_accounts chart_of_accounts { get; set; }
    }
}
