//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.invoice_item = new HashSet<invoice_item>();
            this.invoice_payment = new HashSet<invoice_payment>();
        }
    
        public int invoice_id { get; set; }
        public int contact_id { get; set; }
        public string invoice_number { get; set; }
        public string invoice_date { get; set; }
        public string order_number { get; set; }
        public int terms_id { get; set; }
        public Nullable<int> sales_person_id { get; set; }
        public Nullable<double> discount_percent { get; set; }
        public Nullable<decimal> discount_value { get; set; }
        public Nullable<int> tax_id { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<bool> amount_tax_inclusive { get; set; }
        public decimal subtotal { get; set; }
        public Nullable<decimal> net_amount { get; set; }
        public Nullable<decimal> shipment_fee { get; set; }
        public Nullable<System.DateTime> shipment_date { get; set; }
        public string shipment_via { get; set; }
        public string note { get; set; }
        public Nullable<int> ref_payment_made_type_id { get; set; }
        public System.DateTime auto_entry_date { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual ref_payment_made_type ref_payment_made_type { get; set; }
        public virtual user user { get; set; }
        public virtual tax_code tax_code { get; set; }
        public virtual term term { get; set; }
        public virtual ICollection<invoice_item> invoice_item { get; set; }
        public virtual ICollection<invoice_payment> invoice_payment { get; set; }
    }
}
