//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_payment
    {
        public int invoice_payment_id { get; set; }
        public int deposit_account_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime payment_date { get; set; }
        public Nullable<System.DateTime> auto_entry_date { get; set; }
        public int ref_payment_mode_id { get; set; }
        public string reference_no { get; set; }
        public string notes { get; set; }
    
        public virtual chart_of_accounts chart_of_accounts { get; set; }
        public virtual invoice invoice { get; set; }
        public virtual ref_payment_mode ref_payment_mode { get; set; }
    }
}
