//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_item
    {
        public int invoice_item_id { get; set; }
        public int invoice_id { get; set; }
        public int item_id { get; set; }
        public double quantity { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<double> discount_percent { get; set; }
        public Nullable<decimal> discount_value { get; set; }
        public Nullable<int> tax_id { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<int> seq { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual item item { get; set; }
        public virtual tax_code tax_code { get; set; }
    }
}
