//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.invoice_item = new HashSet<invoice_item>();
        }
    
        public int item_id { get; set; }
        public string name { get; set; }
        public string SKU { get; set; }
        public string description { get; set; }
        public Nullable<decimal> buy_price { get; set; }
        public Nullable<decimal> sell_price { get; set; }
        public Nullable<bool> sell_price_tax_inclusive { get; set; }
        public Nullable<int> tax_id { get; set; }
        public Nullable<int> sales_account { get; set; }
        public Nullable<int> purchase_account { get; set; }
        public bool active { get; set; }
    
        public virtual chart_of_accounts chart_of_accounts { get; set; }
        public virtual chart_of_accounts chart_of_accounts1 { get; set; }
        public virtual ICollection<invoice_item> invoice_item { get; set; }
        public virtual tax_code tax_code { get; set; }
    }
}
