//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class manual_adjustment_item
    {
        public int manual_adjustment_item_id { get; set; }
        public int manual_adjustment_id { get; set; }
        public int chart_of_accounts_id { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public string memo { get; set; }
        public Nullable<int> seq { get; set; }
    
        public virtual chart_of_accounts chart_of_accounts { get; set; }
        public virtual manual_adjustment manual_adjustment { get; set; }
    }
}
