//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class manual_adjustment
    {
        public manual_adjustment()
        {
            this.manual_adjustment_item = new HashSet<manual_adjustment_item>();
        }
    
        public int manual_adjustment_id { get; set; }
        public System.DateTime date { get; set; }
        public string ref_no { get; set; }
        public string memo { get; set; }
        public System.DateTime auto_entry_date { get; set; }
    
        public virtual ICollection<manual_adjustment_item> manual_adjustment_item { get; set; }
    }
}
