//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int profile_id { get; set; }
        public string company_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string trade_registration_no { get; set; }
        public string tax_no { get; set; }
        public string gst_no { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string website { get; set; }
        public Nullable<System.DateTime> current_financial_year { get; set; }
        public Nullable<System.DateTime> financial_year_start { get; set; }
        public Nullable<System.DateTime> financial_year_end { get; set; }
        public string currency_code { get; set; }
        public string product_version { get; set; }
        public string GAF_version { get; set; }
    
        public virtual currency currency { get; set; }
    }
}
