//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_payment_mode
    {
        public ref_payment_mode()
        {
            this.invoice_payment = new HashSet<invoice_payment>();
        }
    
        public int ref_payment_mode_id { get; set; }
        public string name { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<invoice_payment> invoice_payment { get; set; }
    }
}
