//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_contact_type
    {
        public ref_contact_type()
        {
            this.contacts = new HashSet<contact>();
        }
    
        public int ref_contact_type_id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<contact> contacts { get; set; }
    }
}
