//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_account_type
    {
        public ref_account_type()
        {
            this.account_type = new HashSet<account_type>();
        }
    
        public int ref_account_type_id { get; set; }
        public string type { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<account_type> account_type { get; set; }
    }
}
