//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_payment_made_type
    {
        public ref_payment_made_type()
        {
            this.expenses = new HashSet<expense>();
            this.invoices = new HashSet<invoice>();
        }
    
        public int ref_payment_made_type_id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<expense> expenses { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
