//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_code
    {
        public tax_code()
        {
            this.chart_of_accounts = new HashSet<chart_of_accounts>();
            this.expenses = new HashSet<expense>();
            this.expense_item = new HashSet<expense_item>();
            this.invoices = new HashSet<invoice>();
            this.invoice_item = new HashSet<invoice_item>();
            this.items = new HashSet<item>();
        }
    
        public int tax_code_id { get; set; }
        public string tax_codename { get; set; }
        public string tax_code_desc { get; set; }
        public string tax_type { get; set; }
        public string tax_type_desc { get; set; }
        public bool purchase_taxable { get; set; }
        public Nullable<double> purchase_tax_rate { get; set; }
        public bool supply_taxable { get; set; }
        public Nullable<double> supply_tax_rate { get; set; }
        public string registration_no { get; set; }
        public string tax_agency { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<int> purchase_account_id { get; set; }
        public Nullable<int> supply_account_id { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<chart_of_accounts> chart_of_accounts { get; set; }
        public virtual chart_of_accounts chart_of_accounts1 { get; set; }
        public virtual chart_of_accounts chart_of_accounts2 { get; set; }
        public virtual ICollection<expense> expenses { get; set; }
        public virtual ICollection<expense_item> expense_item { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual ICollection<invoice_item> invoice_item { get; set; }
        public virtual ICollection<item> items { get; set; }
    }
}
