//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class term
    {
        public term()
        {
            this.invoices = new HashSet<invoice>();
        }
    
        public int term_id { get; set; }
        public string term_name { get; set; }
        public int allowance { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
